# Generated by Django 5.1.7 on 2025-03-10 09:40

import assessment.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("Cardiologist", "Cardiologist"),
                            ("Dermatologist", "Dermatologist"),
                            ("Gastroenterologist", "Gastroenterologist"),
                            ("General Practitioner", "General Practitioner"),
                            ("Neurologist", "Neurologist"),
                            ("Oncologist", "Oncologist"),
                            ("Ophthalmologist", "Ophthalmologist"),
                            ("Orthopedic Surgeon", "Orthopedic Surgeon"),
                            ("Otolaryngologist", "Otolaryngologist"),
                            ("Pediatrician", "Pediatrician"),
                            ("Psychiatrist", "Psychiatrist"),
                            ("Urologist", "Urologist"),
                        ],
                        default="General Practitioner",
                        max_length=20,
                    ),
                ),
                ("hospital", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_pressure", models.CharField(max_length=20)),
                ("cholesterol", models.CharField(max_length=20)),
                ("bmi", models.FloatField()),
                ("diabetes_history", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assessment.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Record",
                "verbose_name_plural": "Health Records",
            },
        ),
        migrations.CreateModel(
            name="MedicalTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, validators=[assessment.models.TestNameValidator]
                    ),
                ),
                ("result", models.CharField(max_length=255)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "health_records",
                    models.ManyToManyField(blank=True, to="assessment.healthrecord"),
                ),
            ],
            options={
                "verbose_name": "Medical Test",
                "verbose_name_plural": "Medical Tests",
            },
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="medical_tests",
            field=models.ManyToManyField(blank=True, to="assessment.medicaltest"),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "date_of_birth",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.date(1950, 1, 1)
                            )
                        ]
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("medical_history", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["full_name"],
            },
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assessment.patient"
            ),
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("diabetes", "diabetes"),
                            ("hypertension", "hypertension"),
                        ],
                        max_length=30,
                    ),
                ),
                ("risk_score", models.FloatField()),
                ("prediction_date", models.DateField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.doctor",
                    ),
                ),
                (
                    "health_record",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.healthrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prediction",
                "verbose_name_plural": "Predictions",
            },
        ),
    ]
